# Generated by Django 5.0.3 on 2024-03-05 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fName", models.CharField(max_length=30)),
                ("lName", models.CharField(max_length=40)),
                ("grade", models.FloatField()),
                ("startDate", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
